# Generated by Django 3.0.7 on 2020-12-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialevents', '0002_auto_20201230_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertask',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
