# Generated by Django 3.0.7 on 2021-02-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimalmix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixplan',
            name='parameters_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='optimalmix/input/'),
        ),
        migrations.AddField(
            model_name='mixtask',
            name='parameters',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
