# Generated by Django 3.0.7 on 2020-10-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourcompensator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourcompensatorplan',
            name='balance_attach',
        ),
        migrations.AddField(
            model_name='hourcompensatorplan',
            name='amount_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/input/amount/'),
        ),
        migrations.AlterField(
            model_name='hourcompensatorplan',
            name='curve_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/input/curve/'),
        ),
        migrations.AlterField(
            model_name='hourcompensatorplan',
            name='schedule_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/input/schedule/'),
        ),
    ]
