# Generated by Django 3.0.7 on 2021-01-21 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hourcompensator', '0005_hourcompensatortask_main_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourcompensatortask',
            name='amount_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/input/'),
        ),
        migrations.AddField(
            model_name='hourcompensatortask',
            name='curve_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/input/'),
        ),
        migrations.AddField(
            model_name='hourcompensatortask',
            name='lock_request',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/http/'),
        ),
        migrations.AddField(
            model_name='hourcompensatortask',
            name='lock_response',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/http/'),
        ),
        migrations.AddField(
            model_name='hourcompensatortask',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='hourcompensatortask',
            name='parameters',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hourcompensatortask',
            name='schedule_attach',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/input/'),
        ),
        migrations.AlterField(
            model_name='hourcompensatortask',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hourcompensator.HourCompensatorPlan'),
        ),
        migrations.CreateModel(
            name='HourCompensatorParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('parameters', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_compensator_parameters', to='accounts.Company')),
            ],
            options={
                'db_table': 'HourCompensatorParameter',
            },
        ),
    ]
