# Generated by Django 3.0.7 on 2021-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourcompensator', '0006_auto_20210121_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourcompensatortask',
            name='execution_warning',
            field=models.TextField(default='{}'),
        ),
    ]
