# Generated by Django 3.0.7 on 2021-03-01 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageMatrixPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'STARTED'), ('F', 'FINISHED'), ('C', 'CANCELLED'), ('E', 'ERROR')], default='P', max_length=1)),
                ('parameters', models.TextField()),
                ('coverage_attach', models.FileField(upload_to='coveragematrix/input/coverage/')),
                ('transactions_attach', models.FileField(upload_to='coveragematrix/input/transactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coveragematrix_plans', to='accounts.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coveragematrix_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CoverageMatrixPlan',
            },
        ),
        migrations.CreateModel(
            name='CoverageMatrixTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('parameters', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('results', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_stack_trace', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='coveragematrix.CoverageMatrixPlan')),
            ],
            options={
                'db_table': 'CoverageMatrixTask',
            },
        ),
    ]
