# Generated by Django 3.0.7 on 2020-12-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertask',
            name='first_row',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivertask',
            name='last_row',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
