# Generated by Django 3.0.7 on 2020-10-23 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourCompensatorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'STARTED'), ('F', 'FINISHED'), ('C', 'CANCELLED'), ('E', 'ERROR')], default='P', max_length=1)),
                ('parameters', models.TextField()),
                ('curve_attach', models.FileField(upload_to='hourcompensator/input/curve/')),
                ('schedule_attach', models.FileField(upload_to='hourcompensator/input/schedule/')),
                ('balance_attach', models.FileField(upload_to='hourcompensator/input/balance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_compensator_plans', to='accounts.Company')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HourCompensatorPlan',
            },
        ),
        migrations.CreateModel(
            name='HourCompensatorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('curves_results', models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/results/curves/')),
                ('compensated_schedules_results', models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/results/compensated_schedules/')),
                ('fixed_curves_results', models.FileField(blank=True, default=None, null=True, upload_to='hourcompensator/results/fixed_curves/')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_stack_trace', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='hourcompensator.HourCompensatorPlan')),
            ],
            options={
                'db_table': 'HourCompensatorTask',
            },
        ),
    ]
